# SwiftLint Configuration for MetaHangulIME

# 기본 규칙 포함
included:
  - Sources
  - Tests

# 제외 경로
excluded:
  - .build
  - .swiftpm
  - Package.swift

# 활성화할 추가 규칙들
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_arrow_whitespace
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

# 비활성화할 규칙들
disabled_rules:
  - todo  # TODO 주석 허용

# 규칙 커스터마이징
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_parameter_count:
  warning: 6
  error: 8

function_body_length:
  warning: 100
  error: 150

trailing_comma:
  mandatory_comma: true

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 2
  max_length:
    warning: 45
    error: 50
  allowed_symbols: ["_"]

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 45
    error: 50
  allowed_symbols: ["_"]
  validates_start_with_lowercase: warning
  excluded:
    - x
    - y
    - z
    - i
    - j
    - k
    - n
    - m
    - id
    - ok
    - to

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

large_tuple:
  warning: 3
  error: 4

# 프로젝트 특화 규칙
file_header:
  required_pattern: |
    \/\/
    \/\/  .*\.swift
    \/\/  MetaHangulIME
    \/\/

# modifier_order 규칙은 SwiftLint 0.53.0부터 기본 설정 사용
